annotations:
  category: Redis Operator
appVersion: 1.1.1
apiVersion: v1
description: A Helm chart for the Spotahome Redis Operator
name: redis-operator
version: 3.1.6
home: https://github.com/spotahome/redis-operator
keywords:
  - "golang"
  - "operator"
  - "cluster"
sources:
  - https://github.com/spotahome/redis-operator
