replicaCount: 1
image: quay.io/spotahome/redis-operator
tag: latest
pullPolicy: Always
team: devops
resources:
  requests:
    cpu: 10m
    memory: 50Mi
  limits:
    cpu: 100m
    memory: 50Mi
rbac:
  install: false
  apiVersion: v1beta1
  imagePullSecrets: []
